### ISSUE TITLE
is this lib support for Typescript?

### ISSUE THREAD

**Issue by wiztensai** [milamer/parse-nested-form-data#1]
- `node` version: v18.13.0
- `npm` version:

Relevant code or config

```ts
import ParseNestedFormData from 'parse-nested-form-data'
```

What you did:
I try to use in typescript

What happened:
The module not imported correctly

```
X [ERROR] No matching export in "node_modules/parse-nested-form-data/dist/parse-nested-form-data.esm.js" for import "default"
```

Suggested solution: i hope the typescript version come in.

**Comment by milamer** [comment]
Heyhey,

I forgot to include instructions on how to import in the documentation. Could you try it like so:

```ts
import { parseFormData } from 'parse-nested-form-data'
```
